"""add missing fields to deprecation and timeline

Revision ID: 0eaa1e5c3ee0
Revises: a1fbcfa70456
Create Date: 2026-03-02 22:32:18.232024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaa1e5c3ee0'
down_revision: Union[str, Sequence[str], None] = 'a1fbcfa70456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deprecation_timeline', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('deprecations', sa.Column('migration_notes', sa.Text(), nullable=True))
    op.add_column('deprecations', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('deprecations', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deprecations', 'created_at')
    op.drop_column('deprecations', 'status')
    op.drop_column('deprecations', 'migration_notes')
    op.drop_column('deprecation_timeline', 'created_at')
    # ### end Alembic commands ###
