"""start time column add

Revision ID: 0ed9a62579ea
Revises: 8b8b9c434ae5
Create Date: 2026-02-27 12:15:52.616218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed9a62579ea'
down_revision: Union[str, Sequence[str], None] = '8b8b9c434ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add columns with a temporary server_default so existing rows get populated
    op.add_column(
        'growth_session',
        sa.Column(
            'start_time',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.add_column(
        'growth_session',
        sa.Column(
            'end_time',
            sa.DateTime(),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    # remove the temporary default now that data has been backfilled
    op.alter_column('growth_session', 'start_time', server_default=None)
    op.alter_column('growth_session', 'end_time', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth_session', 'end_time')
    op.drop_column('growth_session', 'start_time')
    # ### end Alembic commands ###
