"""add_missing_cascade_deletes

Revision ID: 2b3535d45f79
Revises: 3c4f9571e99a
Create Date: 2026-02-22 06:50:02.680219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b3535d45f79'
down_revision: Union[str, Sequence[str], None] = '3c4f9571e99a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop existing foreign key constraints
    op.drop_constraint('team_member_team_id_fkey', 'team_member', type_='foreignkey')
    op.drop_constraint('session_note_session_id_fkey', 'session_note', type_='foreignkey')
    op.drop_constraint('action_items_session_id_fkey', 'action_items', type_='foreignkey')
    
    # Recreate with CASCADE delete
    op.create_foreign_key('team_member_team_id_fkey', 'team_member', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('session_note_session_id_fkey', 'session_note', 'growth_session', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('action_items_session_id_fkey', 'action_items', 'growth_session', ['session_id'], ['id'], ondelete='CASCADE')


    op.alter_column('userr', 'role',
               existing_type=postgresql.ENUM('admin', 'lead', 'developer', 'viewer', name='userrole'),
               type_=sa.Enum('admin', 'lead', 'developer', 'viewer', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userr', 'role',
               existing_type=sa.Enum('admin', 'lead', 'developer', 'viewer', name='userrole', native_enum=False),
               type_=postgresql.ENUM('admin', 'lead', 'developer', 'viewer', name='userrole'),
               existing_nullable=False)
    
    # Drop the CASCADE constraints
    op.drop_constraint('team_member_team_id_fkey', 'team_member', type_='foreignkey')
    op.drop_constraint('session_note_session_id_fkey', 'session_note', type_='foreignkey')
    op.drop_constraint('action_items_session_id_fkey', 'action_items', type_='foreignkey')
    
    # Recreate without CASCADE delete
    op.create_foreign_key('team_member_team_id_fkey', 'team_member', 'team', ['team_id'], ['id'])
    op.create_foreign_key('session_note_session_id_fkey', 'session_note', 'growth_session', ['session_id'], ['id'])
    op.create_foreign_key('action_items_session_id_fkey', 'action_items', 'growth_session', ['session_id'], ['id'])
    # ### end Alembic commands ###
