"""add calendar field to growth session

Revision ID: 39ed81017711
Revises: 2b3535d45f79
Create Date: 2026-02-23 11:43:26.846186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39ed81017711'
down_revision: Union[str, Sequence[str], None] = '2b3535d45f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groth_session_id'), table_name='groth_session')
    op.drop_table('groth_session')
    op.add_column('growth_session', sa.Column('calendar_event_id', sa.String(), nullable=True))
    op.add_column('growth_session', sa.Column('meeting_link', sa.String(), nullable=True))
    op.add_column('growth_session', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('growth_session', 'location')
    op.drop_column('growth_session', 'meeting_link')
    op.drop_column('growth_session', 'calendar_event_id')
    op.create_table('groth_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'COMPLETED', 'CANCLLED', name='sessionstatus'), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('groth_session_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('groth_session_pkey'))
    )
    op.create_index(op.f('ix_groth_session_id'), 'groth_session', ['id'], unique=False)
    # ### end Alembic commands ###
