"""add email_notification_enabled column

Revision ID: 57f305864233
Revises: 3ac4dc23358c
Create Date: 2026-02-24 14:54:52.539708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f305864233'
down_revision: Union[str, Sequence[str], None] = '3ac4dc23358c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'userr',
        sa.Column(
            'email_notification_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userr', 'email_notification_enabled')
    # ### end Alembic commands ###
