"""add notifcation prefrence to user

Revision ID: 80a6cf98044e
Revises: 57f305864233
Create Date: 2026-02-25 12:16:21.564221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a6cf98044e'
down_revision: Union[str, Sequence[str], None] = '57f305864233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userr', sa.Column('email_session_reminder', sa.Boolean(), nullable=True))
    op.add_column('userr', sa.Column('email_action_item_due', sa.Boolean(), nullable=True))
    op.add_column('userr', sa.Column('email_mention', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userr', 'email_mention')
    op.drop_column('userr', 'email_action_item_due')
    op.drop_column('userr', 'email_session_reminder')
    # ### end Alembic commands ###
