"""add technical debt tables

Revision ID: 88ce694975a0
Revises: 80a6cf98044e
Create Date: 2026-02-25 22:32:15.639658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88ce694975a0'
down_revision: Union[str, Sequence[str], None] = '80a6cf98044e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technical_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='debtpriority'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', name='debtstatus'), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('estimated_effort', sa.Integer(), nullable=True),
    sa.Column('actual_effort', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['userr.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_debts_id'), 'technical_debts', ['id'], unique=False)
    op.create_table('debt_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['technical_debts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_comments_id'), 'debt_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debt_comments_id'), table_name='debt_comments')
    op.drop_table('debt_comments')
    op.drop_index(op.f('ix_technical_debts_id'), table_name='technical_debts')
    op.drop_table('technical_debts')
    # ### end Alembic commands ###
