"""add changed_by to debt_status_history

Revision ID: 8b8b9c434ae5
Revises: f1b2c3d4e5f6
Create Date: 2026-02-26 21:39:37.742084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b8b9c434ae5'
down_revision: Union[str, Sequence[str], None] = 'f1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt_status_history', sa.Column('changed_by', sa.Integer(), nullable=False))
    op.add_column('debt_status_history', sa.Column('changed_at', sa.DateTime(), nullable=True))
    op.drop_constraint(op.f('debt_status_history_change_by_fkey'), 'debt_status_history', type_='foreignkey')
    op.create_foreign_key(None, 'debt_status_history', 'userr', ['changed_by'], ['id'])
    op.drop_column('debt_status_history', 'change_at')
    op.drop_column('debt_status_history', 'change_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('debt_status_history', sa.Column('change_by', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('debt_status_history', sa.Column('change_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'debt_status_history', type_='foreignkey')
    op.create_foreign_key(op.f('debt_status_history_change_by_fkey'), 'debt_status_history', 'userr', ['change_by'], ['id'])
    op.drop_column('debt_status_history', 'changed_at')
    op.drop_column('debt_status_history', 'changed_by')
    # ### end Alembic commands ###
