"""Initial migration

Revision ID: 907bfccb9af2
Revises: 97cbdd46cf47
Create Date: 2026-02-17 16:11:51.083045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '907bfccb9af2'
down_revision: Union[str, Sequence[str], None] = '97cbdd46cf47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.add_column('projects', sa.Column('name', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('description', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('status', sa.Enum('active', 'inactive', 'completed', name='project_status'), nullable=True))
    op.add_column('projects', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_foreign_key(None, 'projects', 'team', ['team_id'], ['id'])
    op.drop_column('projects', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_column('projects', 'team_id')
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'name')
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('users_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
