"""add deprecation and deprecation timeline tables

Revision ID: a1fbcfa70456
Revises: e9f9278eed01
Create Date: 2026-03-02 22:20:57.569149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fbcfa70456'
down_revision: Union[str, Sequence[str], None] = 'e9f9278eed01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
