"""add affected_system fields to deprecation

Revision ID: cd6a727c9d34
Revises: 0eaa1e5c3ee0
Create Date: 2026-03-04 11:19:56.823181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd6a727c9d34'
down_revision: Union[str, Sequence[str], None] = '0eaa1e5c3ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deprecation_timeline', 'stage',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('announced', 'warning_added', 'last_support_date', 'removed', name='timelinestage', native_enum=False),
               existing_nullable=False)
    op.add_column('deprecations', sa.Column('affected_system', sa.Text(), nullable=True))
    op.add_column('deprecations', sa.Column('affected_users_count', sa.Integer(), nullable=True))
    op.alter_column('deprecations', 'impact_level',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deprecations', 'impact_level',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('deprecations', 'affected_users_count')
    op.drop_column('deprecations', 'affected_system')
    op.alter_column('deprecation_timeline', 'stage',
               existing_type=sa.Enum('announced', 'warning_added', 'last_support_date', 'removed', name='timelinestage', native_enum=False),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)
    # ### end Alembic commands ###
