"""fix typo in action_items title column

Revision ID: d150a7b7473c
Revises: 5ba1af2713f4
Create Date: 2026-02-20 23:43:08.165612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd150a7b7473c'
down_revision: Union[str, Sequence[str], None] = '5ba1af2713f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_groth_session_id'), table_name='groth_session')
    # drop foreign keys that reference the old misspelled table before dropping it
    op.drop_constraint(op.f('action_items_session_id_fkey'), 'action_items', type_='foreignkey')
    op.drop_constraint(op.f('session_note_session_id_fkey'), 'session_note', type_='foreignkey')
    op.drop_table('groth_session')
    op.add_column('action_items', sa.Column('title', sa.String(), nullable=False))
    op.create_foreign_key(None, 'action_items', 'growth_session', ['session_id'], ['id'])
    op.drop_column('action_items', 'titlr')
    op.create_foreign_key(None, 'session_note', 'growth_session', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_note', type_='foreignkey')
    op.create_foreign_key(op.f('session_note_session_id_fkey'), 'session_note', 'groth_session', ['session_id'], ['id'])
    op.add_column('action_items', sa.Column('titlr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'action_items', type_='foreignkey')
    op.create_foreign_key(op.f('action_items_session_id_fkey'), 'action_items', 'groth_session', ['session_id'], ['id'])
    op.drop_column('action_items', 'title')
    op.create_table('groth_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PLANNED', 'COMPLETED', 'CANCLLED', name='sessionstatus'), autoincrement=False, nullable=True),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], name=op.f('groth_session_team_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('groth_session_pkey'))
    )
    op.create_index(op.f('ix_groth_session_id'), 'groth_session', ['id'], unique=False)
    # ### end Alembic commands ###
