"""add deprecation and deprecation timeline tables

Revision ID: e9f9278eed01
Revises: 0ed9a62579ea
Create Date: 2026-03-02 22:20:00.156468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e9f9278eed01'
down_revision: Union[str, Sequence[str], None] = '0ed9a62579ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deprecation_timeline', 'stage',
               existing_type=postgresql.ENUM('announced', 'warning_added', 'removed', name='timelinestage'),
               type_=sa.Enum('announced', 'warning_added', 'removed', name='timelinestage', native_enum=False),
               existing_nullable=False)
    op.add_column('deprecations', sa.Column('type', sa.Enum('api', 'feature', 'library', 'database', 'tool', name='deprecationtype', native_enum=False), nullable=False))
    op.drop_column('deprecations', 'deprecation_type_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deprecations', sa.Column('deprecation_type_enum', postgresql.ENUM('api', 'feature', 'library', 'database', 'tool', name='deprecationtype'), autoincrement=False, nullable=False))
    op.drop_column('deprecations', 'type')
    op.alter_column('deprecation_timeline', 'stage',
               existing_type=sa.Enum('announced', 'warning_added', 'removed', name='timelinestage', native_enum=False),
               type_=postgresql.ENUM('announced', 'warning_added', 'removed', name='timelinestage'),
               existing_nullable=False)
    # ### end Alembic commands ###
