"""Initial migration

Revision ID: 1791ec1065c9
Revises: 
Create Date: 2026-04-08 18:12:08.896598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1791ec1065c9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email_notification_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_session_reminder', sa.Boolean(), nullable=True),
    sa.Column('email_action_item_due', sa.Boolean(), nullable=True),
    sa.Column('email_mention', sa.Boolean(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'lead', 'developer', 'viewer', name='userrole', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userr_email'), 'userr', ['email'], unique=True)
    op.create_index(op.f('ix_userr_id'), 'userr', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['userr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['userr.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_table('growth_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'completed', 'cancelled', name='sessionstatus', native_enum=False), nullable=True),
    sa.Column('calendar_event_id', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_growth_session_id'), 'growth_session', ['id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'completed', name='projectstatus', native_enum=False), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['userr.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_member_id'), 'team_member', ['id'], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'pending', 'completed', name='action_status', native_enum=False), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['growth_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_items_id'), 'action_items', ['id'], unique=False)
    op.create_table('deprecations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('api', 'feature', 'library', 'database', 'tool', name='deprecationtype', native_enum=False), nullable=False),
    sa.Column('current_version', sa.String(length=50), nullable=False),
    sa.Column('deprecated_in', sa.String(length=50), nullable=False),
    sa.Column('removal_planned_for', sa.String(length=50), nullable=False),
    sa.Column('replacement', sa.String(length=255), nullable=True),
    sa.Column('migration_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('affected_system', sa.Text(), nullable=True),
    sa.Column('affected_users_count', sa.Integer(), nullable=True),
    sa.Column('impact_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deprecations_id'), 'deprecations', ['id'], unique=False)
    op.create_table('session_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['growth_session.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_note_id'), 'session_note', ['id'], unique=False)
    op.create_table('technical_debts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='debtpriority'), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'resolved', 'identified', 'wont_fix', name='debtstatus'), nullable=True),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('estimated_effort', sa.Integer(), nullable=True),
    sa.Column('actual_effort', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['userr.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_debts_id'), 'technical_debts', ['id'], unique=False)
    op.create_table('debt_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debt_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['technical_debts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['userr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_comments_id'), 'debt_comments', ['id'], unique=False)
    op.create_table('debt_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('technical_debt_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=True),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['userr.id'], ),
    sa.ForeignKeyConstraint(['technical_debt_id'], ['technical_debts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_status_history_id'), 'debt_status_history', ['id'], unique=False)
    op.create_table('deprecation_debt_link',
    sa.Column('deprecation_id', sa.Integer(), nullable=True),
    sa.Column('debt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['debt_id'], ['technical_debts.id'], ),
    sa.ForeignKeyConstraint(['deprecation_id'], ['deprecations.id'], )
    )
    op.create_table('deprecation_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deprecation_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('announced', 'warning_added', 'last_support_date', 'removed', name='timelinestage', native_enum=False), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deprecation_id'], ['deprecations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deprecation_timeline_id'), 'deprecation_timeline', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deprecation_timeline_id'), table_name='deprecation_timeline')
    op.drop_table('deprecation_timeline')
    op.drop_table('deprecation_debt_link')
    op.drop_index(op.f('ix_debt_status_history_id'), table_name='debt_status_history')
    op.drop_table('debt_status_history')
    op.drop_index(op.f('ix_debt_comments_id'), table_name='debt_comments')
    op.drop_table('debt_comments')
    op.drop_index(op.f('ix_technical_debts_id'), table_name='technical_debts')
    op.drop_table('technical_debts')
    op.drop_index(op.f('ix_session_note_id'), table_name='session_note')
    op.drop_table('session_note')
    op.drop_index(op.f('ix_deprecations_id'), table_name='deprecations')
    op.drop_table('deprecations')
    op.drop_index(op.f('ix_action_items_id'), table_name='action_items')
    op.drop_table('action_items')
    op.drop_index(op.f('ix_team_member_id'), table_name='team_member')
    op.drop_table('team_member')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_growth_session_id'), table_name='growth_session')
    op.drop_table('growth_session')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_userr_id'), table_name='userr')
    op.drop_index(op.f('ix_userr_email'), table_name='userr')
    op.drop_table('userr')
    # ### end Alembic commands ###
